url: http://docs.textpattern.io
timezone: Europe/London
permalink: none
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
author: The Textpattern Development Team and contributors
twitter:
  username: textpattern
