permalink: none
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://textpattern.github.io/'
  relativeLinks: 'http://textpattern.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add tags"
          placeholder: "Choose tags"
          options:
            - name: "Installation"
              value: "installation"
            - name: "Configuration"
              value: "configuration"
            - name: "Tag reference"
              value: "tag-reference"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
